[package]
name = "iced-timer-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {versoin = "0.10.0", features = ["smol"]}
